### ISSUE TITLE
Saving a file removes needed imports

### ISSUE THREAD

**Issue by willfaught** [syscrusher/golang.tmbundle#16]
I've noticed in the past day or two that saving a file will appear to goimports-format it, as it removes imports, however those imports are actually needed to build. Not sure what's going on here, I would expect goimports to work the same whether it's hooked into the file-save feature or run manually through the bundle menu or keyboard shortcut.

**Comment by nathany** [comment]
Hm.  I've had problems with goimports removing needed imports in the past, but I haven't had any trouble with the current version. So you're saying it behaves differently than on the command line? Do you perhaps have multiple copies of goimports with TextMate picking up an outdated copy?

Do you have TM_GOFMT set to the full path to goimports?

**Comment by willfaught** [comment]
I saw that my TM_GODOC was pointing to /usr/local/Cellar/go/1.4.1/libexec/bin/godoc, which no longer exists. Not sure if that's related, don't see how it could be, but I fixed it to point to 1.5.1, the version I have installed now.

I now have:

TM_GOCODE=/Users/myuser/bin/gocode
TM_GODOC=/usr/local/Cellar/go/1.5.1/libexec/bin/godoc
TM_GOFMT=/Users/myuser/bin/goimports
TM_GOPATH=/Users/myuser

Are those right? I kind of fumbled through setting stuff to get things to work.

I don't see the problem right now in the files I have open, but I'll post back here if I see it again in the next few days.

Thanks for responding!

**Comment by willfaught** [comment]
Come to think of it, it would be really helpful for the README to say which environment variables should be set to what.

**Comment by nathany** [comment]
Yes, it sure would. Or at least what environment variables there are to set. The values will depend on how you installed Go, but perhaps there could be suggestions for the common installations?

I bet @syscrusher would accept a PR. :wink:

**Comment by willfaught** [comment]
Still seeing it. For example:

    $ go build
    $
    [Save with no changes in TextMate, which removes an import]
    $ go build
    # my/import/path
    ./foo.go:123: undefined: bar in baz.Boz
    $ goimports -e -l -w
    foo.go
    $ go build
    $

Don't know if this could be related, but the import removed is for a package with a name different than its directory name (e.g. directory "go-foo" for package "foo").

**Comment by willfaught** [comment]
I'm seeing some strange behavior. If I Ctrl-Shift-H (goimports), the package with the name that doesn't match the directory name (e.g. go-foo) immediately disappears, then the editor freezes for a couple seconds (I suspect this is because it's a somewhat large file) and then the import pops in again. I can keep invoking goimports like that it over and over and that happens every time. If I Cmd-S save, it removes the import but doesn't bring it back, and saving again doesn't change anything. If I goimports after that, it behaves as described before.

**Comment by willfaught** [comment]
Looked into how `goimports` works and figured it out. I removed all variables except `PATH`, prefixed `PATH` with `$PATH:`, and then added the `GOPATH` variable. So now I have:

    PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/go/1.5.1/libexec/bin:/Users/Will/bin
    GOPATH=/Users/Will
