### ISSUE TITLE
Empty TM_GOPATH breaks compilation

### ISSUE THREAD

**Issue by tg** [syscrusher/golang.tmbundle#17]
When `TM_GOPATH` is not set, the resulting gopath is `:$GOPATH`. The leading colon seems to make go1.5 interpret this as a relative path and compilations end up with following errors:

```go: GOPATH entry is relative; must be absolute path: "".
Run 'go help gopath' for usage.```

This can be verified by running go build from command line:

```
$ GOPATH=:/go go build
go: GOPATH entry is relative; must be absolute path: "".
Run 'go help gopath' for usage.
```

The issue was fixed by me and cherry-picked in https://github.com/syscrusher/golang.tmbundle/commit/cf4a25062bf453ca1a46a4ad7ef7ff01740f350b

The change was then reverted by cherry-pick of https://github.com/syscrusher/golang.tmbundle/commit/26538901bcb6253660bf4fab52dbc336ed984e2c

Anyone else faces similar issue or having problems with fix proposed in cf4a25062bf453ca1a46a4ad7ef7ff01740f350b?

**Comment by syscrusher** [comment]
D'oh. My bad, and my apologies. I was not careful enough while merging your changes and then @fmccann's git&mercurial changes. I believe your fix was fine. I will reapply and push shortly.

**Comment by tg** [comment]
Not a problem, was just wondering whether anyone is seeing similar error to mine as this is basically preventing from building/running anything. Although maybe people are using `TM_GOPATH` variable which "fixes" the issue.

**Comment by syscrusher** [comment]
I remember having this issue when I first started using TM&go, resolved it by setting TM_GOPATH, then went on blissfully ignorant :)

**Comment by tg** [comment]
Thanks for fixing. Closing.
