### ISSUE TITLE
Doesn't work for me at all

### ISSUE THREAD

**Issue by hleinders** [syscrusher/golang.tmbundle#23]
I can't get this bundle to work. My go environment is set up properly, it works fine on the command line (using go version go1.5.2 darwin/amd64 from macports, GOROOT=/opt/local/lib/go, GOPATH=$HOME/Source/Go). I've installed all the tools via "go get" as found on the golang site and also refreshed them according to your README. After fiddling around with my problems I've also done a fresh install of TextMate (2.0-beta.8.5) and reinstalled the Go bundle with the preference pane. 
My OS is 10.11.2 with all updates installed.

My Problems are:
* can't edit any go file. As soon as I save a file or do a goimports (CTRL-SHIFT-H or Menu item) or a gofmt (Menu item), all my changes are lost and the file reverts to the state where I've opened it.

* can't build or install. When I try to build a program or module, even a simple $GOPATH/src/Hello/main.go with a simple "Hello Word"-Statement, I get a "can't load package: package /Users/xxxx/Source/Go/src/Hello: import "/Users/xxxx/Source/Go/src/Hello": cannot import absolute path".

I've tried to set all the TM_GO-Vars in the README, tried also to set only PATH and GOPATH or TM_GOPATH, and a lot of combinations. I've also double checked that only one "goimports" can be found and all tools work well if called directly on the shell prompt. I'm really stuck here. 

The only thing that really works is "run". Is there any debug mode where I could find more information?
BTW, I've none of the TM_GO_DYNAMIC* vars set.

**Comment by hleinders** [comment]
Another BTW, I definitely do hope I made a really dumb mistake. I'd love to get this working. :-)

**Comment by hleinders** [comment]
Hi again,

a quickfix _for me_ would be to prevent pushing 'pkg' to args (gomate.rb:54). But maybe I've missed something fundamental here.

**Comment by syscrusher** [comment]
I apologize for the delay, I've just applied your suggested quickfix. 
I've tried a few times to recreate this issue and failed, but removing gomate.rb:54 also doesn't break things for me. Here's to the best.
