### ISSUE TITLE
Does not show completion windows from go-code

### ISSUE THREAD

**Issue by Spalf** [syscrusher/golang.tmbundle#27]
OS X 10.11.5
TextMate version 2.0-beta.9
go-code lasted for 2016/05/18
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

Where I press Opt+Esc, the logs from gocode -debug looks fine.
But the TM2 does not show any windows for any completion.
An error, tool tip "No completions found." showed.

Sorry for my Eng.

**Comment by nathany** [comment]
TextMate code completions are case-sensitive using a simple "begins with" match. Could that be why no completions are found, or does it not work at all?

**Comment by Spalf** [comment]
@nathany tnx for your reply.
But I told about the code completions from the gocode daemon.
Gocode's Logs:
`$ gocode -s -debug
2016/05/19 10:18:14 Go project path: .
2016/05/19 10:18:14 Got autocompletion request for ''
2016/05/19 10:18:14 Cursor at: 47
2016/05/19 10:18:14 -------------------------------------------------------
package main

import "fmt"

func main() {
	fmt.#
}
2016/05/19 10:18:14 -------------------------------------------------------
2016/05/19 10:18:14 Found "fmt" at "/usr/local/Cellar/go/1.6.2/libexec/pkg/darwin_amd64/fmt.a"
2016/05/19 10:18:14 Error parsing input file (inner block):
2016/05/19 10:18:14  4:6: expected selector or type assertion, found ';'
2016/05/19 10:18:14 extracted expression tokens: fmt
2016/05/19 10:18:14 Offset: 0
2016/05/19 10:18:14 Number of candidates found: 25
2016/05/19 10:18:14 Candidates are:
2016/05/19 10:18:14   func Errorf(format string, a ...interface{}) error
2016/05/19 10:18:14   func Fprint(w io.Writer, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Fprintf(w io.Writer, format string, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Fprintln(w io.Writer, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Fscan(r io.Reader, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Fscanf(r io.Reader, format string, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Fscanln(r io.Reader, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Print(a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Printf(format string, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Println(a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Scan(a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Scanf(format string, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Scanln(a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Sprint(a ...interface{}) string
2016/05/19 10:18:14   func Sprintf(format string, a ...interface{}) string
2016/05/19 10:18:14   func Sprintln(a ...interface{}) string
2016/05/19 10:18:14   func Sscan(str string, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Sscanf(str string, format string, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   func Sscanln(str string, a ...interface{}) (n int, err error)
2016/05/19 10:18:14   type Formatter interface
2016/05/19 10:18:14   type GoStringer interface
2016/05/19 10:18:14   type ScanState interface
2016/05/19 10:18:14   type Scanner interface
2016/05/19 10:18:14   type State interface
2016/05/19 10:18:14   type Stringer interface
2016/05/19 10:18:14 =======================================================`

25 completions are found, but TM does not show any.

**Comment by nathany** [comment]
Ah, okay. I'm not one of the project maintainers, but I'm sure someone here can look into it with you.

**Comment by Spalf** [comment]
It is [bundle-support.tmbundle](https://github.com/textmate/bundle-support.tmbundle) issue. The lib/ui.rb does not work with ruby 2.0.

I changed ruby version in the "Complete" command to ruby18, its work!
