### ISSUE TITLE
Stopped working Complete command

### ISSUE THREAD

**Issue by msoap** [syscrusher/golang.tmbundle#29]
When complete one variant or without complete suggestions
Screenshots:

For one variant:
<img width="437" alt="screen shot 2016-08-18 at 20 32 52" src="https://cloud.githubusercontent.com/assets/844117/17784113/ea60e74c-6583-11e6-849b-b20a659560d6.png">

Without variants:
<img width="438" alt="screen shot 2016-08-18 at 20 33 42" src="https://cloud.githubusercontent.com/assets/844117/17784116/ef672eb8-6583-11e6-86ce-afa0675f7d49.png">

Broken after #28

**Comment by msoap** [comment]
After revert line:
`require ENV['TM_SUPPORT_PATH'] + "/lib/tm/require_cmd.rb"`

**Comment by syscrusher** [comment]
Thanks. Confirmed and reverted.

I don't understand why yet. Complete.tmcommand doesn't call require_cmd. I'll leave this open to investigate.

**Comment by syscrusher** [comment]
Ah, need to include exit_codes.rb. Will be fixed shortly.

**Comment by msoap** [comment]
Thanks!

**Comment by infininight** [comment]
Sorry about that my fault. Didn't think to check if the libraries includes were being used. Deployed the change so it's already available to everyone using the bundle installer/updater.
