### ISSUE TITLE
Setting TM_GOFMT to goimports binary removes imports with go- prefix

### ISSUE THREAD

**Issue by taterbase** [syscrusher/golang.tmbundle#30]
If TM_GOFMT is set to the `goimports` binary and if you have a file that uses a `go-` prefixed package such as...

```
package main

import(
  "github.com/armon/go-radix"
}

func main() {
  _ := radix.New()
}
```

Saving the file will remove the `go-radix` import leaving it broken. Running `goimports` on it manually does not cause this issue.

**Comment by taterbase** [comment]
I discovered the issue. Right now, the `gofmt` command just evaluates in the shell, allowing STDIN to pass through whatever is defined as `TM_GOFMT`. Usually that would be fine, but for tricky package names such as `go-radix` the `goimports` tool needs more context. Unfortunately, it has no `GOPATH` to go on in the isolated command environment. But it *does* work when running `Imports` directly because it calls the ruby method in `gomate` which *does* set the `GOPATH` environment variable. 

Potential fixes include:
1. adding `GOPATH="${TM_GOPATH}"` to the `Fmt` command.
2. asking users to just set the `GOPATH` environment variable in TextMate.

I think the first is tenable, I'll send a pr asap.

**Comment by syscrusher** [comment]
First solution is reasonable, thanks for debugging and the PR.
