### ISSUE TITLE
Current bundle lacks mandatory keys in property list file

### ISSUE THREAD

**Issue by taterbase** [syscrusher/golang.tmbundle#31]
Forgive me because I am still learning about TextMate Bundles. The current version of this bundle does not import properly due to the above mentioned issue.

![screen shot 2016-09-13 at 11 03 20 pm](https://cloud.githubusercontent.com/assets/940180/18500623/72c09902-7a06-11e6-846e-7582b0b6856f.png)

The commit before the latest `2a503ab09fd0c8bbe75bb0090880d9b6b0afd7a8` does work however (and I'm not yet sure why that is).

**Comment by syscrusher** [comment]
After the merges this should be resolved. Thanks. Let me know if it's not.
