### ISSUE TITLE
Grammar: Invalid includes #storage_type|#storage_modifier

### ISSUE THREAD

**Issue by infininight** [syscrusher/golang.tmbundle#35]
Noticed these when monitoring log output from TextMate. There are two places where `#storage_type` and `#storage_modifier` are both included but neither of these repository items exist. Since they don't do anything they should be removed but wanted to bring it up to make sure they aren't intended to do something.

**Comment by syscrusher** [comment]
I believe it's an attempt to include only storage.type.go and storage.modifier.go from keywords. Only those 2/6 keywords are valid in two locations they're included from. Is there a proper way to include only those two, or is it best to just include all keywords?
