### ISSUE TITLE
Gocode server does not exit with text mate

### ISSUE THREAD

**Issue by pokstad** [syscrusher/golang.tmbundle#41]
Appears that gocode is still running after textmate exits. Also, I'd love to help with improving this plugin if there's any help needed 😄

**Comment by msoap** [comment]
gocode itself exit in 30 minutes, see `close-timeout` in https://github.com/nsf/gocode#options

**Comment by pokstad** [comment]
Where is the gocode server process started? I only see the client process being executed here: https://github.com/syscrusher/golang.tmbundle/blob/master/Commands/Complete.tmCommand#L42
