### ISSUE TITLE
Failure running "run".

### ISSUE THREAD

**Issue by lcowell** [syscrusher/golang.tmbundle#8]
Hi there, I've recently started getting this error when I attempt to run a go file in textmate 2.0-beta.6.7 / 2.0-beta.6.8

I've clone this repo in to `~/Library/Application Support/Avian/Bundles/golang.tmbundle` and as you can see in the output below it is attempting to run the go code using this plugin. Any thoughts on how to trouble-shoot this ?

Error message:
```
~/Library/Application Support/Avian/Bundles/golang.tmbundle/Support/gomate.rb:26:in `go': undefined method `length' for nil:NilClass (NoMethodError)
	from Run:4
```

"edit command" source
```ruby
#!/usr/bin/env ruby18

require "#{ENV['TM_BUNDLE_SUPPORT']}/gomate"
Go::go "run", :verb => "Running"
```

Let me know if there's anything else I can do to help.

**Comment by syscrusher** [comment]
I can't recreate with 2.0-beta.6.8. Can you provide any more information?

**Comment by lcowell** [comment]
Well, here's where it's failing:
```ruby
 file_length = ENV['TM_DIRECTORY'].length + 1
```
It seems like my TM_DIRECTORY should be set, but it isn't (it's nil). Any thoughts on why that might be ?

Here it is with a little context. 
```ruby
    if command == 'run'
      file_length = ENV['TM_DIRECTORY'].length + 1
      go_file = ENV['TM_FILEPATH'][file_length..-1]
      args.push(go_file)
      opts[:chdir] = ENV['TM_DIRECTORY']
      #...
   end

```

**Comment by syscrusher** [comment]
Ah, is this an unsaved file? @tg authored a fix that I just merged.

**Comment by lcowell** [comment]
I just updated to master and it's working again. Thanks!
