### ISSUE TITLE
Documentation doesn't work for types or non-standard packages

### ISSUE THREAD

**Issue by willfaught** [syscrusher/golang.tmbundle#9]
When I highlight `Eligible` below:

    if err := thing.Eligible(c); err != nil {

and press ^H for documentation, this error appears in a temporary popover:

    2015/06/11 15:14:44 open /usr/local/Cellar/go/1.4.2/libexec/src/Evidence: no such file or directory

Is this feature only supposed to work for standard library packages? Can I not get documentation for custom packages, or types in packages (even standard ones)?

**Comment by syscrusher** [comment]
Apologies for the delay. This is a feature the bundle doesn't support yet.
The 'Documentation for Word' command right now simply passes the highlighted word to godoc. By default, godoc doesn't look in your GOPATH, only GOROOT. godoc is also very literal, it won't do searching.
Using github.com/syscrusher/fake as an example: we can't pass fake.FirstName() directly to godoc, we have to find it's import path first. This gets harder if you're not calling the package directly (for example, embedded types).
This is something I hope to improve by reimplementing parts of the bundle directly in go.

**Comment by willfaught** [comment]
>This is something I hope to improve by reimplementing parts of the bundle directly in go.

Is there another issue tracking this work?
